export const LEADER_BOARD_REQUEST = 'LEADER_BOARD_REQUEST';
export const LEADER_BOARD_SUCCESS = 'LEADER_BOARD_SUCCESS';
export const LEADER_BOARD_FAILURE = 'LEADER_BOARD_FAILURE';

export const LEADER_RESULT_REQUEST = 'LEADER_RESULT_REQUEST';
export const LEADER_RESULT_SUCCESS = 'LEADER_BOARD_SUCCESS';
export const LEADER_RESULT_FAILURE = 'LEADER_BOARD_FAILURE';
