export const TOPIC_REQUEST = 'TOPIC_REQUEST';
export const TOPIC_SUCCESS = 'TOPIC_SUCCESS';
export const TOPIC_FAILURE = 'TOPIC_FAILURE';

export const COMMENT_REQUEST = 'COMMENT_REQUEST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAILURE = 'COMMENT_FAILURE';

export const REPLY_REQUEST = 'REPLY_REQUEST';
export const REPLY_SUCCESS = 'REPLY_SUCCESS';
export const REPLY_FAILURE = 'REPLY_FAILURE';

export const EMOTION_REQUEST = 'EMOTION_REQUEST';
export const EMOTION_SUCCESS = 'EMOTION_SUCCESS';
export const EMOTION_FAILURE = 'EMOTION_FAILURE';
