export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_CHECK_FAILURE = 'AUTH_CHECK_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAILURE = 'USER_FAILURE';

export const SIGNIN_REQUEST = 'SIGININ_REQUEST';
export const SIGNIN_SUCCESS = 'SIGININ_SUCCESS';
export const SIGNIN_FAILURE = 'SIGININ_CHECK_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
