export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_CHECK_FAILURE = 'AUTH_CHECK_FAILURE';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'AUTH_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const LOGOUT = 'LOGOUT';

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
