export const LOAD_LEADERBOARD = 'LOAD_LEADERBOARD';
export const LEADERBOARD_REQUEST = 'LEADERBOARD_REQUEST';
export const LEADERBOARD_ERROR = 'LEADERBOARD_ERROR';
export const LEADERBOARD_SUCCESS = 'LEADERBOARD_SUCCESS';
