export const dataMap = {
  posY: [
    {
      row: 1,
      posX: [
        { col: 1, type: 'wall' },
        { col: 2, type: 'wall' },
        { col: 3, type: 'wall' },
        { col: 4, type: 'wall' },
        { col: 5, type: 'wall' },
        { col: 6, type: 'wall' },
        { col: 7, type: 'wall' },
        { col: 8, type: 'wall' },
        { col: 9, type: 'wall' },
        { col: 10, type: 'empty' },
        { col: 11, type: 'empty' },
        { col: 12, type: 'wall' },
        { col: 13, type: 'wall' },
        { col: 14, type: 'wall' },
        { col: 15, type: 'wall' },
        { col: 16, type: 'wall' },
        { col: 17, type: 'wall' },
        { col: 18, type: 'wall' },
        { col: 19, type: 'wall' },
        { col: 20, type: 'wall' }
      ]
    },
    {
      row: 2,
      posX: [
        { col: 1, type: 'wall' },
        { col: 2, type: 'pill' },
        { col: 3, type: 'pill' },
        { col: 4, type: 'pill' },
        { col: 5, type: 'empty' },
        { col: 6, type: 'pill' },
        { col: 7, type: 'pill' },
        { col: 8, type: 'pill' },
        { col: 9, type: 'empty' },
        { col: 10, type: 'pill' },
        { col: 11, type: 'pill' },
        { col: 12, type: 'empty' },
        { col: 13, type: 'pill' },
        { col: 14, type: 'pill' },
        { col: 15, type: 'pill' },
        { col: 16, type: 'empty' },
        { col: 17, type: 'pill' },
        { col: 18, type: 'pill' },
        { col: 19, type: 'pill' },
        { col: 20, type: 'wall' }
      ]
    },
    {
      row: 3,
      posX: [
        { col: 1, type: 'wall' },
        { col: 2, type: 'pill' },
        { col: 3, type: 'pill' },
        { col: 4, type: 'pill' },
        { col: 5, type: 'empty' },
        { col: 6, type: 'empty' },
        { col: 7, type: 'pill' },
        { col: 8, type: 'pill' },
        { col: 9, type: 'pill' },
        { col: 10, type: 'pill' },
        { col: 11, type: 'pill' },
        { col: 12, type: 'pill' },
        { col: 13, type: 'pill' },
        { col: 14, type: 'pill' },
        { col: 15, type: 'empty' },
        { col: 16, type: 'empty' },
        { col: 17, type: 'pill' },
        { col: 18, type: 'pill' },
        { col: 19, type: 'pill' },
        { col: 20, type: 'wall' }
      ]
    },
    {
      row: 4,
      posX: [
        { col: 1, type: 'wall' },
        { col: 2, type: 'empty' },
        { col: 3, type: 'empty' },
        { col: 4, type: 'pill' },
        { col: 5, type: 'pill' },
        { col: 6, type: 'pill' },
        { col: 7, type: 'pill' },
        { col: 8, type: 'empty' },
        { col: 9, type: 'empty' },
        { col: 10, type: 'pill' },
        { col: 11, type: 'pill' },
        { col: 12, type: 'empty' },
        { col: 13, type: 'empty' },
        { col: 14, type: 'pill' },
        { col: 15, type: 'pill' },
        { col: 16, type: 'pill' },
        { col: 17, type: 'pill' },
        { col: 18, type: 'empty' },
        { col: 19, type: 'empty' },
        { col: 20, type: 'wall' }
      ]
    },
    {
      row: 5,
      posX: [
        { col: 1, type: 'wall' },
        { col: 2, type: 'pill' },
        { col: 3, type: 'pill' },
        { col: 4, type: 'empty' },
        { col: 5, type: 'pill' },
        { col: 6, type: 'pill' },
        { col: 7, type: 'pill' },
        { col: 8, type: 'empty' },
        { col: 9, type: 'pill' },
        { col: 10, type: 'empty' },
        { col: 11, type: 'empty' },
        { col: 12, type: 'pill' },
        { col: 13, type: 'empty' },
        { col: 14, type: 'pill' },
        { col: 15, type: 'pill' },
        { col: 16, type: 'pill' },
        { col: 17, type: 'empty' },
        { col: 18, type: 'pill' },
        { col: 19, type: 'pill' },
        { col: 20, type: 'wall' }
      ]
    },
    {
      row: 6,
      posX: [
        { col: 1, type: 'empty' },
        { col: 2, type: 'empty' },
        { col: 3, type: 'empty' },
        { col: 4, type: 'empty' },
        { col: 5, type: 'pill' },
        { col: 6, type: 'pill' },
        { col: 7, type: 'pill' },
        { col: 8, type: 'pill' },
        { col: 9, type: 'empty' },
        { col: 10, type: 'empty' },
        { col: 11, type: 'empty' },
        { col: 12, type: 'empty' },
        { col: 13, type: 'pill' },
        { col: 14, type: 'pill' },
        { col: 15, type: 'pill' },
        { col: 16, type: 'pill' },
        { col: 17, type: 'empty' },
        { col: 18, type: 'empty' },
        { col: 19, type: 'empty' },
        { col: 20, type: 'empty' }
      ]
    },
    {
      row: 7,
      posX: [
        { col: 1, type: 'empty' },
        { col: 2, type: 'empty' },
        { col: 3, type: 'empty' },
        { col: 4, type: 'empty' },
        { col: 5, type: 'empty' },
        { col: 6, type: 'empty' },
        { col: 7, type: 'empty' },
        { col: 8, type: 'empty' },
        { col: 9, type: 'pill' },
        { col: 10, type: 'pill' },
        { col: 11, type: 'pill' },
        { col: 12, type: 'pill' },
        { col: 13, type: 'empty' },
        { col: 14, type: 'empty' },
        { col: 15, type: 'empty' },
        { col: 16, type: 'empty' },
        { col: 17, type: 'empty' },
        { col: 18, type: 'empty' },
        { col: 19, type: 'empty' },
        { col: 20, type: 'empty' }
      ]
    },
    {
      row: 8,
      posX: [
        { col: 1, type: 'wall' },
        { col: 2, type: 'empty' },
        { col: 3, type: 'empty' },
        { col: 4, type: 'empty' },
        { col: 5, type: 'empty' },
        { col: 6, type: 'pill' },
        { col: 7, type: 'pill' },
        { col: 8, type: 'pill' },
        { col: 9, type: 'pill' },
        { col: 10, type: 'pill' },
        { col: 11, type: 'pill' },
        { col: 12, type: 'pill' },
        { col: 13, type: 'pill' },
        { col: 14, type: 'pill' },
        { col: 15, type: 'empty' },
        { col: 16, type: 'empty' },
        { col: 17, type: 'empty' },
        { col: 18, type: 'empty' },
        { col: 19, type: 'empty' },
        { col: 20, type: 'wall' }
      ]
    },
    {
      row: 9,
      posX: [
        { col: 1, type: 'wall' },
        { col: 2, type: 'empty' },
        { col: 3, type: 'empty' },
        { col: 4, type: 'pill' },
        { col: 5, type: 'pill' },
        { col: 6, type: 'empty' },
        { col: 7, type: 'empty' },
        { col: 8, type: 'empty' },
        { col: 9, type: 'pill' },
        { col: 10, type: 'pill' },
        { col: 11, type: 'pill' },
        { col: 12, type: 'empty' },
        { col: 13, type: 'empty' },
        { col: 14, type: 'empty' },
        { col: 15, type: 'empty' },
        { col: 16, type: 'pill' },
        { col: 17, type: 'pill' },
        { col: 18, type: 'empty' },
        { col: 19, type: 'empty' },
        { col: 20, type: 'wall' }
      ]
    },
    {
      row: 10,
      posX: [
        { col: 1, type: 'wall' },
        { col: 2, type: 'pill' },
        { col: 3, type: 'pill' },
        { col: 4, type: 'pill' },
        { col: 5, type: 'empty' },
        { col: 6, type: 'empty' },
        { col: 7, type: 'pill' },
        { col: 8, type: 'pill' },
        { col: 9, type: 'pill' },
        { col: 10, type: 'pill' },
        { col: 11, type: 'pill' },
        { col: 12, type: 'pill' },
        { col: 13, type: 'pill' },
        { col: 14, type: 'pill' },
        { col: 15, type: 'empty' },
        { col: 16, type: 'empty' },
        { col: 17, type: 'pill' },
        { col: 18, type: 'pill' },
        { col: 19, type: 'pill' },
        { col: 20, type: 'wall' }
      ]
    },
    {
      row: 11,
      posX: [
        { col: 1, type: 'wall' },
        { col: 2, type: 'pill' },
        { col: 3, type: 'pill' },
        { col: 4, type: 'pill' },
        { col: 5, type: 'empty' },
        { col: 6, type: 'pill' },
        { col: 7, type: 'pill' },
        { col: 8, type: 'pill' },
        { col: 9, type: 'empty' },
        { col: 10, type: 'pill' },
        { col: 11, type: 'pill' },
        { col: 12, type: 'empty' },
        { col: 13, type: 'pill' },
        { col: 14, type: 'pill' },
        { col: 15, type: 'pill' },
        { col: 16, type: 'empty' },
        { col: 17, type: 'pill' },
        { col: 18, type: 'pill' },
        { col: 19, type: 'pill' },
        { col: 20, type: 'wall' }
      ]
    },
    {
      row: 12,
      posX: [
        { col: 1, type: 'wall' },
        { col: 2, type: 'wall' },
        { col: 3, type: 'wall' },
        { col: 4, type: 'wall' },
        { col: 5, type: 'wall' },
        { col: 6, type: 'wall' },
        { col: 7, type: 'wall' },
        { col: 8, type: 'wall' },
        { col: 9, type: 'wall' },
        { col: 10, type: 'empty' },
        { col: 11, type: 'empty' },
        { col: 12, type: 'wall' },
        { col: 13, type: 'wall' },
        { col: 14, type: 'wall' },
        { col: 15, type: 'wall' },
        { col: 16, type: 'wall' },
        { col: 17, type: 'wall' },
        { col: 18, type: 'wall' },
        { col: 19, type: 'wall' },
        { col: 20, type: 'wall' }
      ]
    }
  ]
};
