name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: check stylelint
        run: npm run lint:style

      - name: check typescript
        run: npm run lint:ts

      - name: check test
        run: npm run test
